import { ApiProperty } from "@nestjs/swagger";
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";


@Entity()
export class Institute {
  @PrimaryGeneratedColumn()
  @ApiProperty({ description: "University ID (autogenerated)" })
  id: number;

  @Column()
  @ApiProperty({ description: "Name of the University" })
  name: string;

  @Column("float")
  @ApiProperty({ description: "Latitude of the University" })
  lat: number;

  @Column("float")
  @ApiProperty({ description: "Longitude of the University" })
  lng: number;

  @Column("text", { array: true })
  @ApiProperty({
    description: "List of courses offered by the university",
    type: [String],
  })
  courses: string[];
}
